services:
    db_msql:
        image: mcr.microsoft.com/mssql/server:latest
        env_file: ".env"
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_PID=Developer
            - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
        ports:
            - 1433:1433
        profiles:
            - mssql
    db_postgres:
        image: bitnami/postgresql:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${POSTGRES_NAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        profiles:
            - postgres
    db_cassandra:
        image: cassandra:latest
        ports:
            - 7000:7000
            - 7001:7001
            - 9042:9042
        profiles:
            - cassandra
            - cassandra-init
        environment:
            - CASSANDRA_AUTHENTICATOR=PasswordAuthenticator
            - CASSANDRA_PASSWORD_SEEDER=yes
            - CASSANDRA_USER=${CASSANDRA_USER}
            - CASSANDRA_PASSWORD=${CASSANDRA_PASSWORD}
        # volumes:
            # - ./cassandra/init/init.cql:/scripts/data.cql
            # - ./cassandra/init:/docker-entrypoint-initdb.d
        # https://stackoverflow.com/a/51476148
        healthcheck:
            test: ["CMD", "cqlsh", "-u db_cassandra", "-p ${CASSANDRA_PASSWORD}" ,"-e describe keyspaces"]
            interval: 15s
            timeout: 10s
            retries: 10
    db_cassandra_init:
        image: cassandra:latest
        profiles:
            - cassandra-init
        environment:
            - CQLSH_HOST=db_cassandra
        depends_on:
            db_cassandra:
                condition: service_started
        volumes:
            - ./cassandra/init:/init
        command: /bin/bash -c "sleep 30 && echo 'loading cassandra keyspace...' && cqlsh db_cassandra 9042 -f /init/init.cql && echo 'keyspace initialized.'"

    db_mongo:
        image: mongo
        profiles:
            - mongo
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
        command:
            - '--config'
            - '/etc/mongo/mongod.yaml'
        volumes:
            - ./mongo/config:/etc/mongo/:ro
            - ./mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro